(()=>{
 const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
 const tab=el('button','Brendlər');tab.id='brandsTab';tab.className='admin-tab';document.querySelector('.admin-tabs').append(tab);
 const view=el('section');view.id='brandsView';view.hidden=true;document.getElementById('productView').before(view);
 const style=el('style');style.textContent='#brandsView[hidden]{display:none}#brandsView form{display:flex;gap:14px;flex-wrap:wrap;align-items:end;padding:20px 0}#brandsView label{display:grid;gap:6px}#brandsView input:not([type=checkbox]){padding:10px;border:1px solid #ddd;border-radius:8px}#brandsView table{width:100%;border-collapse:collapse}#brandsView td,#brandsView th{padding:12px;text-align:left;border-bottom:1px solid #eee}#brandsView img{width:64px;height:48px;object-fit:contain}#brandsView button{margin-right:8px}#brandsView .brand-table-wrap{overflow:auto}';document.head.append(style);
 view.innerHTML='<h2>Brendlər</h2><p>Brend adını dəyişdikdə bağlı məhsullar da yenilənir.</p><form id="brandForm"><label>Brend adı<input name="name" required maxlength="100"></label><label>Loqo (PNG, JPG, WebP · maksimum 2 MB)<input name="logo" type="file" accept="image/png,image/jpeg,image/webp"></label><label>Sıra<input name="position" type="number" min="0" max="100000" value="1000" required></label><label><span>Ana səhifədə göstər</span><input name="active" type="checkbox"></label><button class="btn-primary" type="submit">Əlavə et</button><button id="brandCancel" class="btn-ghost" type="button" hidden>Ləğv et</button></form><p id="brandStatus" role="status"></p><label>Axtar<input id="brandSearch" type="search" placeholder="Brend adı"></label><div class="brand-table-wrap"><table><thead><tr><th>Loqo</th><th>Brend</th><th>Ana səhifə</th><th>Sıra</th><th>Əməliyyatlar</th></tr></thead><tbody></tbody></table></div>';
 const form=view.querySelector('form'),body=view.querySelector('tbody'),status=view.querySelector('#brandStatus'),search=view.querySelector('#brandSearch'),save=form.querySelector('[type=submit]'),cancel=view.querySelector('#brandCancel');let rows=[],editing=null,busy=false;
 function reset(){editing=null;form.reset();save.textContent='Əlavə et';cancel.hidden=true;}
 async function request(path='',options={}){const r=await fetch('/api/brands'+path,{cache:'no-store',...options,headers:authHeaders()});const data=await r.json();if(!r.ok)throw Error(data.message||'Brendlər yüklənmədi.');return data;}
 function render(){body.replaceChildren();for(const b of rows.filter(b=>b.name.toLocaleLowerCase('az').includes(search.value.toLocaleLowerCase('az')))){
  const tr=el('tr'),logo=el('td');if(b.image){const img=el('img');img.src=b.image;img.alt=b.name;logo.append(img);}else logo.textContent='—';tr.append(logo,el('td',b.name),el('td',b.active?'Göstərilir':'Gizlidir'),el('td',b.position));const actions=el('td');
  const edit=el('button','Redaktə et');edit.className='btn-ghost';edit.onclick=()=>{if(busy)return;editing=b.id;form.elements.name.value=b.name;form.elements.position.value=b.position;form.elements.active.checked=b.active;form.elements.logo.value='';save.textContent='Yadda saxla';cancel.hidden=false;form.scrollIntoView({block:'center',behavior:'smooth'});};
  const remove=el('button','Sil');remove.className='btn-ghost';remove.onclick=async()=>{if(busy||!confirm(b.name+' brendi silinsin?'))return;busy=true;remove.disabled=true;try{await request('/'+b.id,{method:'DELETE'});if(editing===b.id)reset();await load();await refreshAdminBrands();status.textContent='Brend silindi.';}catch(e){status.textContent=e.message;}finally{busy=false;remove.disabled=false;}};actions.append(edit,remove);tr.append(actions);body.append(tr);
 }}
 async function load(){status.textContent='Yüklənir...';try{rows=await request();render();status.textContent=rows.length+' brend';}catch(e){status.textContent=e.message;}}
 form.onsubmit=async e=>{e.preventDefault();if(busy||!form.reportValidity())return;const file=form.elements.logo.files[0];if(file&&file.size>2*1024*1024){status.textContent='Loqo maksimum 2 MB olmalıdır.';return;}const data=new FormData(form);data.set('active',String(form.elements.active.checked));if(!file)data.delete('logo');busy=true;save.disabled=true;try{await request(editing?'/'+editing:'',{method:editing?'PATCH':'POST',body:data});reset();await load();await refreshAdminBrands();await loadProducts();status.textContent='Brend saxlanıldı.';}catch(e){status.textContent=e.message;}finally{busy=false;save.disabled=false;}};
 cancel.onclick=()=>{if(!busy)reset();};search.oninput=render;
 const others=['productsTab','homeSectionsTab','chatsTab','usersTab','creditOrdersTab'];
 tab.onclick=()=>{document.querySelectorAll('.admin-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');for(const id of ['productView','homeSectionsView','chatView','creditOrdersView'])document.getElementById(id).style.display='none';document.getElementById('usersView').hidden=true;view.hidden=false;clearTimeout(chatRefreshTimer);adminChatStreamAbort?.abort();load();};
 for(const id of others)document.getElementById(id).addEventListener('click',()=>{view.hidden=true;tab.classList.remove('active');});
 document.getElementById('logoutBtn').addEventListener('click',()=>{view.hidden=true;rows=[];body.replaceChildren();reset();});
})();

