ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "firstName" TEXT,
  ADD COLUMN IF NOT EXISTS "lastName" TEXT,
  ADD COLUMN IF NOT EXISTS "birthDate" DATE;
ALTER TABLE "OtpChallenge" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'sent',
  ADD COLUMN IF NOT EXISTS "registrationUsedAt" TIMESTAMP(3);
